import Head from "next/head";
import { useRouter } from "next/router";
import Header from "../components/Header";

function Search() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Search Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      <h1>Search page</h1>
      {/* Search Results */}
    </div>
  );
}

export default Search;
